<?php

return [
    'uuid' => ['type' => '?string'],
    'id' => ['type' => '?int'],
    'name' => ['type' => '?string'],
    'type' => ['type' => '?string'],
    'repositoryUrl' => ['type' => '?string'],
    'repositoryProvider' => ['type' => '?string'],
    'authenticationUser' => ['type' => '?string'],
    'organizationUuid' => ['type' => '?string'],
    'sshKey' => ['type' => '?string'],
    'aesKey' => ['type' => '?string'],
    'createdAt' => ['type' => '?string'],
    'updatedAt' => ['type' => '?string'],
    'teamIds' => ['type' => 'int[]|null'],
    'branchMatch' => ['type' => '?string'],
    'branches' => ['type' => 'string[]|null'],
    'buildOnPrOnly' => ['type' => '?bool'],
    'setupCommands' => ['type' => 'string[]|null'],
    'deploymentPipelines' => ['type' => '\Thiagorb\Codeship\Responses\Organizations\Projects\DeploymentPipeline[]|null'],
    'environmentVariables' => ['type' => '\Thiagorb\Codeship\Responses\Organizations\Projects\EnvironmentVariable[]|null'],
    'testPipelines' => ['type' => '\Thiagorb\Codeship\Responses\Organizations\Projects\TestPipeline[]|null'],
    'notificationRules' => ['type' => '\Thiagorb\Codeship\Responses\Organizations\Projects\NotificationRule[]|null'],
];